receivers:
  snmp:
    collection_interval: 20s
    endpoint: 'udp://localhost:161'
    version: v2c
    community: community
    resource_attributes:
  otel-snmp.sysName:
    scalar_oid: "1.3.6.1.2.1.1.5.0"
  otel-snmp.sysDescr:
    scalar_oid: ".1.3.6.1.2.1.1.1.0"

attributes:
  otel-snmp.IF-MIB.ifDescr:
    oid: "1.3.6.1.2.1.2.2.1.2"
  otel-snmp.IF-MIB.ifType:
    oid: "1.3.6.1.2.1.2.2.1.3"
  otel-snmp.IF-MIB.ifMtu:
    oid: "1.3.6.1.2.1.2.2.1.4"
  otel-snmp.IF-MIB.ifSpeed:
    oid: "1.3.6.1.2.1.2.2.1.5"
  otel-snmp.IF-MIB.ifAdminStatus:
    oid: "1.3.6.1.2.1.2.2.1.7"
  otel-snmp.IF-MIB.ifOperStatus:
    oid: "1.3.6.1.2.1.2.2.1.8"

metrics:
  otel-snmp.IF-MIB.ifInOctets:
    description: "Interface Incoming Bytes"
    unit: "By"
    sum:
      aggregation: cumulative
      monotonic: true
      value_type: int
    column_oids:
      - oid: "1.3.6.1.2.1.2.2.1.10"
        attributes:
          - name: otel-snmp.IF-MIB.ifDescr
          - name: otel-snmp.IF-MIB.ifType
          - name: otel-snmp.IF-MIB.ifMtu
          - name: otel-snmp.IF-MIB.ifSpeed
          - name: otel-snmp.IF-MIB.ifAdminStatus
          - name: otel-snmp.IF-MIB.ifOperStatus
        resource_attributes:
          - otel-snmp.sysName
          - otel-snmp.sysDescr
  otel-snmp.IF-MIB.ifOutOctets:
